server:
  port: 9999
spring:
  application:
    name: topaz-tree
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://192.168.10.243:5432/topazshop
    username: topaz
    password: office
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update